### ISSUE TITLE
I can't see the "Image" module when I try to run...

### ISSUE THREAD

**Issue by AustinDamn** [jhenkens/CS176C-Homework-4#1]
Hello, thanks you share the code first,
    but I cant's see the "Image" module... 
    or something I do wrong?  could you tell me ? thanks!
# 

Traceback (most recent call last):
  File "D:\python\Stream_Sample\CS176C-Homework-4-master\ClientLauncher.py", line 3, in <module>
    from Client import Client
  File "D:\python\Stream_Sample\CS176C-Homework-4-master\Client.py", line 3, in <module>
    import Image, ImageTk
ImportError: No module named Image

**Comment by SunnerLi** [comment]
My environment is Ubuntu14.04.
Try the following command on the shell:

```
sudo apt-get install python-tk python-imaging-tk
```

As I encounter the same problem, the command solved.
